# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: lab4

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'

steps:
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'custom'
#     custom: 'msbuild'
#     arguments: '/t:UpdateAssemblyInfo'
#   displayName: 'Set Assembly Manifest Data'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.4'
  displayName: 'Use NuGet 6.4'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: 'NuGet Restore'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:Platform="Any CPU"'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
  displayName: 'Build Solution'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: $(buildConfiguration)
    versioningScheme: 'off'
  displayName: 'NuGet Pack'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
