# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: lab4

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.4'
  displayName: 'Use NuGet 6.4'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: 'NuGet Restore'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:Platform="Any CPU"'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
  displayName: 'Build Solution'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: $(buildConfiguration)
    versioningScheme: 'off'
  displayName: 'NuGet Pack'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '08692c93-c23e-462c-8ffe-3befd1a3f868/5c3efca0-2433-4545-b46c-23d40ef393a6'
  displayName: 'NuGet Push'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
